# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AdaHome Dot Dev
email: ada@adahome.dev
description: >- # this means to ignore newlines until "baseurl:"
  A software engineer and her notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://site.adahome.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Ch4ni

# set the in-use theme
theme: bulma-clean-theme
ignore_theme_config: true
theme_color: '#902299'
fixed_navbar: top
#force_theme: light

highlighter: rouge
gist:
  noscript: false

# configuration for bulma-clean-theme
lang: en

# configure jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
  #- jekyll-commonmark-ghpages

# markdown customization for github pages
# this is for the 'jekyll-commonmark-ghpages' plugin.
# https://github.com/github/jekyll-commonmark-ghpages?tab=readme-ov-file#installation
#markdown: CommonMarkGhPages
#markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# set the default format for post permalinks
# see jekyll docs for more details: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty

# default values for front-matter.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - 
    scope:
      path: ""
      type: posts
    values:
      author: chani
      show_sidebar: false
